export const countries = [
  { country: "Ireland", continent: "Europe", language: "English" },
  { country: "Spain", continent: "Europe", language: "Spanish" },
  { country: "United Kingdom", continent: "Europe", language: "English" },
  { country: "France", continent: "Europe", language: "French" },
  { country: "Germany", continent: "Europe", language: "German" },
  { country: "Luxembourg", continent: "Europe", language: "French" },
  { country: "Sweden", continent: "Europe", language: "Swedish" },
  { country: "Norway", continent: "Europe", language: "Norwegian" },
  { country: "Italy", continent: "Europe", language: "Italian" },
  { country: "Greece", continent: "Europe", language: "Greek" },
  { country: "Iceland", continent: "Europe", language: "Icelandic" },
  { country: "Portugal", continent: "Europe", language: "Portuguese" },
  { country: "Malta", continent: "Europe", language: "Maltese" },
  { country: "Brazil", continent: "South America", language: "Portuguese" },
  { country: "Argentina", continent: "South America", language: "Spanish" },
  { country: "Colombia", continent: "South America", language: "Spanish" },
  { country: "Peru", continent: "South America", language: "Spanish" },
  { country: "Venezuela", continent: "South America", language: "Spanish" },
  { country: "Uruguay", continent: "South America", language: "Spanish" },
  { country: "Belgium", continent: "Europe", language: "French" },
];

export const COUNTRY_CODES = {
  Ireland: "ie",
  Luxembourg: "lu",
  Belgium: "be",
  Spain: "es",
  "United Kingdom": "gb",
  France: "fr",
  Germany: "de",
  Sweden: "se",
  Italy: "it",
  Greece: "gr",
  Iceland: "is",
  Portugal: "pt",
  Malta: "mt",
  Norway: "no",
  Brazil: "br",
  Argentina: "ar",
  Colombia: "co",
  Peru: "pe",
  Venezuela: "ve",
  Uruguay: "uy",
};

export const firstNames = [
  "Tony",
  "Andrew",
  "Kevin",
  "Bricker",
  "Dimple",
  "Gil",
  "Sophie",
  "Isabelle",
  "Emily",
  "Olivia",
  "Lily",
  "Chloe",
  "Isabella",
  "Amelia",
  "Jessica",
  "Sophia",
  "Ava",
  "Charlotte",
  "Mia",
  "Lucy",
  "Grace",
  "Ruby",
  "Ella",
  "Evie",
  "Freya",
  "Isla",
  "Poppy",
  "Daisy",
  "Layla",
];

export const lastNames = [
  "Smith",
  "Connell",
  "Flanagan",
  "McGee",
  "Unalkat",
  "Lopes",
  "Beckham",
  "Black",
  "Braxton",
  "Brennan",
  "Brock",
  "Bryson",
  "Cadwell",
  "Cage",
  "Carson",
  "Chandler",
  "Cohen",
  "Cole",
  "Corbin",
  "Dallas",
  "Dalton",
  "Dane",
  "Donovan",
  "Easton",
  "Fisher",
  "Fletcher",
  "Grady",
  "Greyson",
  "Griffin",
  "Gunner",
  "Hayden",
  "Hudson",
  "Hunter",
  "Jacoby",
  "Jagger",
  "Jaxon",
  "Jett",
  "Kade",
  "Kane",
  "Keating",
  "Keegan",
  "Kingston",
  "Kobe",
];
